site:
  title: CPPython
  start_page: cppython::index.adoc
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
output:
  dir: ./dist
  clean: true